sudo: false
dist: bionic
language: python
group: edge

services:
  - xvfb

matrix:
  include:
    - os: linux
      python: 3.10
      env: TESTENV=py310-pyqt640 QT_API=pyqt6 PEP8=1 COV=1
  fast_finish: true

before_install:
  - sudo apt update
  - sudo apt -y install ffmpeg
  - export DISPLAY=:99.0
  - sleep 3

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/videomorph/videomorph/.cache

install:
  - pip install pip --upgrade
  - pip install pytest pytest-cov black flake8 pep8-naming flake8-debugger flake8-docstrings codecov
  - pip install PyQt6==6.4.0

script:
  - flake8 --select=D1 videomorph/*.py
  - black --check videomorph/*.py

after_success:
  - pytest --cov=videomorph/ --cov-report=xml
  - codecov
