# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Building

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install FFMPEG
      run: |
        sudo apt-get update
        sudo apt-get -y install ffmpeg
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nose pytest pytest-cov black flake8 pep8-naming flake8-debugger flake8-docstrings codecov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Download Sample Video
      run: |
        wget -c https://isorepublic.com/wp-content/uploads/2019/01/iso-republic-free-video-085.mp4 -O ./sample-video.mp4
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check code style with Black
      run: |
        black --check ./
    - name: Test with pytest
      run: |
        python -m pytest tests/ --cov=videomorph/ --cov-report=xml
